massdriver-cloud/massdriver-cli

pkg/application/parse_test.go
pkg/application/testdata/appdeps.yaml
pkg/application/types.go

This helps answer the question around the iam `condition` per role in the Security Bloc [design doc](https://massdriver.slab.com/posts/artifact-security-blocks-vbnzyvvh#h0p17-gcp).
```
{
"security": {
"iam": {
"read-bq": {
"roles": ["roles/bq.read"],
"condition": "etc.."
},
"read-gcs": {
"roles": ["roles/gcs.read"],
"condition": "etc.."
}
}
}
}
```

updating policy field to support an array

---

pkg/generator/templates/terraform/.gitignore

I left our Massdriver ignores at the bottom, but I use this site for every gitignore now. Sometimes I have to add things (like our MD ignores) but for common frameworks, OSSs, etc it's really solid. 
I also moved the tf lock ignore to the Massdriver section, thoughts?
Site:
https://www.toptal.com/developers/gitignore
The gitignore I added (change the url and you'll get different ignores)
https://www.toptal.com/developers/gitignore/api/terraform,osx,windows,linux

using mostly generated gitignore, adding osx, windows, linux

---

cmd/bundle.go
pkg/application/package.go
pkg/bundle/parse.go
pkg/bundle/parse_test.go
pkg/bundle/schema_test.go

Enable the ability to override `access` on `mass bundle publish`.
This will allow us in CI to override the value so we can keep sandbox bundles private and official bundles public.

Cmd line override of access

---

.github/workflows/test.yaml
pkg/bundle/parse.go
pkg/bundle/parse_test.go
pkg/bundle/templates/terraform/massdriver.yaml

We should default the steps to `src` and `terraform` when not present in the file and exclude them from the bundle generator.
This will let us hide this feature from users for now so people don't depend on it since it can be destructive in the even they change their `path`.
It also makes the standard bundle file a little shorter for something the average users won't need to change.

Default steps if not present

---

pkg/bundle/templates/terraform/.pre-commit-config.yaml

Keep changes like this in sync w/ our bundles via something like this:
https://github.com/massdriver-cloud/bundle-github-repo-manager/pull/7

Allow precommit to pass if there are no AWS args in the env

---

pkg/definition/get.go
pkg/jsonschema/hydrate.go
pkg/jsonschema/hydrate_test.go

See the comments below for the yamls I used to test after writing tests for these. 
I checked:
- massdriver ref
- added code, added test
- http ref
- added code, added test 
- local ref
- the error was already informative, so I didn't add anything. 
I didn't check these changes in, but when an error is returned, CLI usage is printed out. I haven't seen this before in a CLI for an error, just for improper usage. When you type `mass bun build` then a helpful message is displayed. I think it's a better experience to not show usage when there's an internal CLI error.
*existing*
```
mass bundle build
{"level":"error","error":"open /Users/wbeebe/repos/massdriver-cloud/_test-hydrate/types/my-local-yolo-type.json: no such file or directory","time":"2022-07-09T15:10:31-07:00","message":"an error …
```

provide more info for 404 of artifacts

---

.github/workflows/release.yaml

from: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
```
Note: The prereleased type will not trigger for pre-releases published from draft releases, but the published type will trigger. If you want a workflow to run when stable and pre-releases publish, subscribe to published instead of released and prereleased.
```

test release workflow on pre-release

---

.github/workflows/release.yaml

this seems to be preventing shell env var expansion in release flow

remove double quotes on ldflags

---

.github/workflows/release.yaml

ok this finally fixes our release flow
you can check it out for yourself by looking at this pre-release https://github.com/massdriver-cloud/massdriver-cli/releases/tag/v0.1.1-rc.7
downloaded artifact should produce this expected output for the most recent commit to the branch
```
$ ~/Downloads/mass version
mass version: v0.1.1-rc.7 (git SHA: 55ac1a330b3bc47c05022cfcf3316d9781291ca4)
```

double braces, deduplicate runs

---

pkg/application/package_test.go
pkg/bundle/publish_test.go
pkg/client/client.go
pkg/client/request.go
pkg/definition/get_test.go
pkg/definition/publish_test.go
pkg/jsonschema/hydrate_test.go

Add the ability to override the Massdriver API URL using an environment variable (`MASSDRIVER_URL`). This allow us to use local development servers for artifacts or other capabilities.
Relates to: https://github.com/massdriver-cloud/artifact-definitions/pull/100

Add capability to override Massdriver API base URL with environment variable

---

pkg/bundle/templates/terraform/Makefile

add `make release` target to follow our tagging convention and generate release notes.

add make release to template

---

cmd/application.go
pkg/cache/application.go

* [Changed] cache to use private functions to access the cache for manipulating files.
* [Added] `MD_DEV_TEMPLATES_PATH` that will alter the templates reader for local development of templates

Support for overriding App template reader func for local tmpl dev

---

pkg/application/prompt.go

Hides [`alpha`](https://github.com/massdriver-cloud/application-templates/tree/main/alpha/aws-ec2) templates from display.
To opt-in:
```shell
mass app template refresh
MD_DEV_TEMPLATES_PATH="~/work/application-templates/alpha" mass app new
```

Hide alpha templates from display

---

pkg/api/package.go

this is needed after migration of graphql IDs https://massdriverworkspace.slack.com/archives/C025G1FEAF9/p1663646627594459

hot fix orgID s/String/ID/ in package getPackage query

---

.github/workflows/release.yaml

this should make re-running a release workflow not fail on asset name conflict.

overwrite release assets

---

pkg/bundle/templates/terraform/src/_artifacts.tf

Ran into this generating a bundle.

remove deprecated "type" argument from artifact resource

---

cmd/application.go
cmd/deploy.go

also deprecates top-level deploy command (with message that we will remove in the future)

move deploy under app

---

pkg/bundle/templates/terraform/massdriver.yaml

`mass bundle new` then `mass bundle build` breaks, because the template doesn't have any named examples.

fix so template builds on first run

---

pkg/provisioners/terraform/compile.go
pkg/provisioners/terraform/compile_test.go
pkg/provisioners/terraform/testdata/testbundle/src/_params.auto.tfvars.json

Some bundles expect `md_metadta.deployment.id`. Adding this to the boilerplate for our bundle devs.

add more to default md_metadata

---

cmd/application.go

I don't think we need to read the `massdriver.yaml` here, and it's not currently used. Removing this makes `mass app deploy` more CI-able.

run mass app deploy without a massdriver.yaml file

---

pkg/application/prompt.go
pkg/bundle/prompt.go

This is fixing some issues I've scene customers run into when setting up apps.
Apps are likely stored in the same directory as the application code itself, so a `massdriver` subdirectory (`app/massdriver/massdriver.yaml`) makes more sense than using the application name as the subdirectory (`app/app/massdriver.yaml`).
If the description field is empty it gets rejected by the API, so we should prevent empty descriptions when creating a new app/bundle.

Mass app new require description
